export const SEARCH_VIDEO = 'SEARCH_VIDEO';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const VIEW_PLAYLIST = 'VIEW_PLAYLIST';
export const DELETE_PLAYLIST_VIDEO = 'DELETE_PLAYLIST_VIDEO';
